# Generated by Django 5.0.13 on 2025-12-18 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
