# Generated by Django 5.0.7 on 2024-07-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_factura_empleado_remove_factura_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='000-000-0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=20),
            preserve_default=False,
        ),
    ]
