# Generated by Django 5.0.13 on 2026-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20251218_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
